package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

var updateConfig bool

var reposCmd = &cobra.Command{
	Use:   "repos",
	Short: "Repository management commands",
}

var reposSyncCmd = &cobra.Command{
	Use:   "sync",
	Short: "Sync the locally tracked repositories list",
	Long:  "Scans the workspace root for Git repositories. Use --update-config to append newly discovered repos to pi-cluster-configs/apps.config.",
	Run: func(cmd *cobra.Command, args []string) {
		syncRepos()
	},
}

func init() {
	rootCmd.AddCommand(reposCmd)
	reposCmd.AddCommand(reposSyncCmd)
	reposSyncCmd.Flags().BoolVarP(&updateConfig, "update-config", "u", false, "Update the apps.config.template with newly discovered repositories")
}

func syncRepos() {
	workspaceRoot := ResolveWorkspaceRoot()

	fmt.Printf("🔄 Scanning workspace at %s for Git repositories...\n", workspaceRoot)

	// Build the repos.sh content
	var builder strings.Builder
	builder.WriteString("#!/bin/bash\n")
	builder.WriteString("# Shared Repository List for Git Utilities\n")
	builder.WriteString("# Auto-generated by kelvin-cli repos sync\n\n")
	builder.WriteString("SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n")
	builder.WriteString("WORKSPACE_ROOT=\"$(cd \"$SCRIPT_DIR/../..\" && pwd)\"\n\n")
	builder.WriteString("# Central definition of all active repositories in the workspace\n")
	builder.WriteString("REPOS=(\n")

	entries, err := os.ReadDir(workspaceRoot)
	if err != nil {
		fmt.Printf("❌ Error reading workspace root: %v\n", err)
		os.Exit(1)
	}

	// Extract names and sort them
	var folderNames []string
	for _, entry := range entries {
		folderNames = append(folderNames, entry.Name())
	}
	sort.Strings(folderNames)

	var validRepoNames []string
	count := 0
	for _, name := range folderNames {
		targetPath := filepath.Join(workspaceRoot, name)

		// Ensure it's a directory
		info, err := os.Stat(targetPath)
		if err != nil || !info.IsDir() {
			continue
		}

		// Check for .git
		gitPath := filepath.Join(targetPath, ".git")
		gitInfo, err := os.Stat(gitPath)
		if err == nil && gitInfo.IsDir() {
			builder.WriteString(fmt.Sprintf("  \"$WORKSPACE_ROOT/%s\"\n", name))
			fmt.Printf("  Found: %s\n", name)
			validRepoNames = append(validRepoNames, name)
			count++
		}
	}

	builder.WriteString(")\n")

	// Write to repos.sh in the kelvinbward/scripts directory
	targetScriptsDir := filepath.Join(workspaceRoot, "kelvinbward", "scripts")
	if err := os.MkdirAll(targetScriptsDir, 0755); err != nil {
		fmt.Printf("❌ Failed to ensure scripts directory: %v\n", err)
		os.Exit(1)
	}

	reposShPath := filepath.Join(targetScriptsDir, "repos.sh")
	if err := os.WriteFile(reposShPath, []byte(builder.String()), 0755); err != nil {
		fmt.Printf("❌ Failed to write repos.sh: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Finished generating repos.sh with %d repositories.\n", count)

	if updateConfig {
		updateAppsConfigTemplate(workspaceRoot, validRepoNames)
	}
}

func updateAppsConfigTemplate(workspaceRoot string, foundRepos []string) {
	templatePath := filepath.Join(workspaceRoot, "pi-cluster-configs", "apps.config")
	content, err := os.ReadFile(templatePath)
	if err != nil {
		fmt.Printf("❌ Failed to read apps.config: %v\n", err)
		return
	}
	templateText := string(content)

	var newApps []string
	var newBlocks strings.Builder

	for _, name := range foundRepos {
		if name == "pi-cluster-configs" || name == ".github" || name == "kelvinbward" {
			continue // System repos
		}

		repoDir := filepath.Join(workspaceRoot, name)

		// Check for Dockerfile
		if _, err := os.Stat(filepath.Join(repoDir, "Dockerfile")); os.IsNotExist(err) {
			continue // Skip repositories without a Dockerfile
		}

		// Derive identifier first — dedup by it, not by URL.
		// This correctly handles https:// vs git@github.com: URL variants of the same
		// remote, and apps that have no remote origin set yet (newly scaffolded).
		identifier := strings.ToUpper(strings.ReplaceAll(name, "-", ""))

		if strings.Contains(templateText, fmt.Sprintf("APP_%s_ENABLED=", identifier)) {
			continue // Already registered
		}

		// Get remote origin — best-effort, new apps may not have one yet
		urlCmd := execCommand("git", "config", "--get", "remote.origin.url")
		urlCmd.Dir = repoDir
		out, _ := urlCmd.Output()
		repoURL := strings.TrimSpace(string(out))
		if repoURL == "" {
			repoURL = "# TODO: set remote origin"
		}

		newApps = append(newApps, identifier)

		newBlocks.WriteString(fmt.Sprintf("\n# --- APP: %s ---\n", identifier))
		newBlocks.WriteString(fmt.Sprintf("APP_%s_ENABLED=true\n", identifier))
		newBlocks.WriteString(fmt.Sprintf("APP_%s_REPO=\"%s\"\n", identifier, repoURL))
		newBlocks.WriteString(fmt.Sprintf("APP_%s_DIR=\"apps/%s\"\n", identifier, strings.ToLower(name)))
		newBlocks.WriteString(fmt.Sprintf("APP_%s_MODE=\"cluster\"\n", identifier))
	}

	if len(newApps) == 0 {
		fmt.Println("✅ apps.config.template is already up to date.")
		return
	}

	// Update the REGISTERED_APPS array — guard against appending duplicates
	lines := strings.Split(templateText, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "REGISTERED_APPS=(") {
			trimmed := strings.TrimSuffix(strings.TrimSpace(line), ")")
			for _, app := range newApps {
				if !strings.Contains(trimmed, fmt.Sprintf("\"%s\"", app)) {
					trimmed += fmt.Sprintf(" \"%s\"", app)
				}
			}
			trimmed += ")"
			lines[i] = trimmed
			break
		}
	}

	newTemplateText := strings.Join(lines, "\n") + newBlocks.String()

	if err := os.WriteFile(templatePath, []byte(newTemplateText), 0644); err != nil {
		fmt.Printf("❌ Failed to update apps.config.template: %v\n", err)
	} else {
		fmt.Printf("🚀 Added %d new applications to apps.config.template: %v\n", len(newApps), newApps)
	}
}
