#!/bin/bash
# Shared Repository List for Git Utilities
# Auto-generated by sync_repos.py

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Central definition of all active repositories in the workspace
REPOS=(
  "$WORKSPACE_ROOT/.github"
  "$WORKSPACE_ROOT/3D-Printing"
  "$WORKSPACE_ROOT/clipboard-spoke"
  "$WORKSPACE_ROOT/creativeAudioJS"
  "$WORKSPACE_ROOT/goobface"
  "$WORKSPACE_ROOT/kelvinbward"
  "$WORKSPACE_ROOT/middleware"
  "$WORKSPACE_ROOT/pi-cluster-configs"
  "$WORKSPACE_ROOT/resume"
)
