import os
import sys

def main():
    # SCRIPT_DIR is the directory where this python script lives
    script_dir = os.path.dirname(os.path.abspath(__file__))
    workspace_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
    repos_sh_path = os.path.join(script_dir, "repos.sh")

    print(f"🔄 Scanning workspace at {workspace_root} for Git repositories...")

    # We will build the contents of repos.sh in memory first
    lines = [
        "#!/bin/bash",
        "# Shared Repository List for Git Utilities",
        "# Auto-generated by sync_repos.py",
        "",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"',
        "",
        "# Central definition of all active repositories in the workspace",
        "REPOS=("
    ]

    count = 0
    
    # Iterate over items in the workspace root
    try:
        items = sorted(os.listdir(workspace_root))
    except Exception as e:
        print(f"❌ Error reading workspace root: {e}")
        sys.exit(1)

    for item in items:
        item_path = os.path.join(workspace_root, item)
        git_path = os.path.join(item_path, ".git")
        
        if os.path.isdir(item_path) and os.path.isdir(git_path):
            lines.append(f'  "$WORKSPACE_ROOT/{item}"')
            print(f"  Found: {item}")
            count += 1
            
    lines.append(")")
    
    # Write to target file
    try:
        with open(repos_sh_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        
        # Make it executable
        os.chmod(repos_sh_path, 0o755)
        
        print(f"✅ Finished generating repos.sh with {count} repositories.")
    except Exception as e:
        print(f"❌ Error writing repos.sh: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
